// -*- tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 2 -*-
// vi: set et ts=4 sw=2 sts=2:
//
// WARNING
// This file is automatically generated by gausslobatto.mac! Don't edit by hand!
#ifndef DUNE_GEOMETRY_QUADRATURE_GaussLobatto_HH
#define DUNE_GEOMETRY_QUADRATURE_GaussLobatto_HH

#ifndef DUNE_INCLUDING_IMPLEMENTATION
#error This is a private header that should not be included directly.
#error Use #include <dune/geometry/quadraturerules.hh> instead.
#endif

namespace Dune {

  /************************************************
   * Quadraturerule for 1d line
   *************************************************/

  template<typename ct>
  class GaussLobattoQuadratureRule : public QuadratureRule<ct,1>
  {
  public:
    /** brief The highest quadrature order available */
    enum { highest_order = 31 };

    using Field = typename QuadraturePoint<ct,1>::Field;
    using Vector = typename QuadraturePoint<ct,1>::Vector;

  private:
    friend class QuadratureRuleFactory<ct,1>;
    GaussLobattoQuadratureRule (int p);
  };

  template<typename ct>
  GaussLobattoQuadratureRule<ct>::GaussLobattoQuadratureRule (int p)
    : QuadratureRule<ct,1>(GeometryTypes::line)
  {
    switch (p)
    {
    // order 0,1
    case 0 :
    case 1 :
      this->order_ = 1;
      this->resize(2);
      (*this)[0] = {
        Vector{0.0L},
        Field{0.5L}};
      (*this)[1] = {
        Vector{1.0L},
        Field{0.5L}};
      break;

    // order 2,3
    case 2 :
    case 3 :
      this->order_ = 3;
      this->resize(3);
      (*this)[0] = {
        Vector{0.0L},
        Field{0.166666666666666666666L}};
      (*this)[1] = {
        Vector{1.0L},
        Field{0.166666666666666666666L}};
      (*this)[2] = {
        Vector{0.5L},
        Field{0.666666666666666666666L}};
      break;

    // order 4,5
    case 4 :
    case 5 :
      this->order_ = 5;
      this->resize(4);
      (*this)[0] = {
        Vector{0.0L},
        Field{0.0833333333333333333333L}};
      (*this)[1] = {
        Vector{1.0L},
        Field{0.0833333333333333333333L}};
      (*this)[2] = {
        Vector{0.72360679774997896964L},
        Field{0.416666666666666666666L}};
      (*this)[3] = {
        Vector{0.276393202250021030359L},
        Field{0.416666666666666666666L}};
      break;

    // order 6,7
    case 6 :
    case 7 :
      this->order_ = 7;
      this->resize(5);
      (*this)[0] = {
        Vector{0.0L},
        Field{0.05L}};
      (*this)[1] = {
        Vector{1.0L},
        Field{0.05L}};
      (*this)[2] = {
        Vector{0.827326835353988571899L},
        Field{0.272222222222222222222L}};
      (*this)[3] = {
        Vector{0.1726731646460114281L},
        Field{0.272222222222222222222L}};
      (*this)[4] = {
        Vector{0.5L},
        Field{0.355555555555555555555L}};
      break;

    // order 8,9
    case 8 :
    case 9 :
      this->order_ = 9;
      this->resize(6);
      (*this)[0] = {
        Vector{1.0L},
        Field{0.0333333333333333333333L}};
      (*this)[1] = {
        Vector{0.0L},
        Field{0.0333333333333333333333L}};
      (*this)[2] = {
        Vector{0.882527661964732346425L},
        Field{0.189237478148923490158L}};
      (*this)[3] = {
        Vector{0.117472338035267653574L},
        Field{0.189237478148923490158L}};
      (*this)[4] = {
        Vector{0.642615758240322548157L},
        Field{0.277429188517743176508L}};
      (*this)[5] = {
        Vector{0.357384241759677451842L},
        Field{0.277429188517743176508L}};
      break;

    // order 10,11
    case 10 :
    case 11 :
      this->order_ = 11;
      this->resize(7);
      (*this)[0] = {
        Vector{1.0L},
        Field{0.0238095238095238095238L}};
      (*this)[1] = {
        Vector{0.0L},
        Field{0.0238095238095238095238L}};
      (*this)[2] = {
        Vector{0.0848880518607165350639L},
        Field{0.138413023680782974005L}};
      (*this)[3] = {
        Vector{0.915111948139283464936L},
        Field{0.138413023680782974005L}};
      (*this)[4] = {
        Vector{0.734424396735357106901L},
        Field{0.215872690604931311708L}};
      (*this)[5] = {
        Vector{0.265575603264642893098L},
        Field{0.215872690604931311708L}};
      (*this)[6] = {
        Vector{0.5L},
        Field{0.243809523809523809523L}};
      break;

    // order 12,13
    case 12 :
    case 13 :
      this->order_ = 13;
      this->resize(8);
      (*this)[0] = {
        Vector{0.0L},
        Field{0.0178571428571428571428L}};
      (*this)[1] = {
        Vector{1.0L},
        Field{0.0178571428571428571428L}};
      (*this)[2] = {
        Vector{0.0641299257451966923312L},
        Field{0.105352113571753019691L}};
      (*this)[3] = {
        Vector{0.935870074254803307668L},
        Field{0.105352113571753019691L}};
      (*this)[4] = {
        Vector{0.204149909283428848927L},
        Field{0.170561346241752182382L}};
      (*this)[5] = {
        Vector{0.795850090716571151072L},
        Field{0.170561346241752182382L}};
      (*this)[6] = {
        Vector{0.395350391048760565615L},
        Field{0.206229397329351940783L}};
      (*this)[7] = {
        Vector{0.604649608951239434384L},
        Field{0.206229397329351940783L}};
      break;

    // order 14,15
    case 14 :
    case 15 :
      this->order_ = 15;
      this->resize(9);
      (*this)[0] = {
        Vector{1.0L},
        Field{0.0138888888888888888888L}};
      (*this)[1] = {
        Vector{0.0L},
        Field{0.0138888888888888888888L}};
      (*this)[2] = {
        Vector{0.949878997705730078656L},
        Field{0.0827476807804027625231L}};
      (*this)[3] = {
        Vector{0.0501210022942699213438L},
        Field{0.0827476807804027625231L}};
      (*this)[4] = {
        Vector{0.838593139755368876722L},
        Field{0.13726935625008086764L}};
      (*this)[5] = {
        Vector{0.161406860244631123277L},
        Field{0.13726935625008086764L}};
      (*this)[6] = {
        Vector{0.318441268086910920644L},
        Field{0.173214255486523172557L}};
      (*this)[7] = {
        Vector{0.681558731913089079355L},
        Field{0.173214255486523172557L}};
      (*this)[8] = {
        Vector{0.5L},
        Field{0.18575963718820861678L}};
      break;

    // order 16,17
    case 16 :
    case 17 :
      this->order_ = 17;
      this->resize(10);
      (*this)[0] = {
        Vector{0.0L},
        Field{0.0111111111111111111111L}};
      (*this)[1] = {
        Vector{1.0L},
        Field{0.0111111111111111111111L}};
      (*this)[2] = {
        Vector{0.959766954083229406914L},
        Field{0.0666529954255350555631L}};
      (*this)[3] = {
        Vector{0.0402330459167705930855L},
        Field{0.0666529954255350555631L}};
      (*this)[4] = {
        Vector{0.130613067447247462498L},
        Field{0.112444671031563226059L}};
      (*this)[5] = {
        Vector{0.869386932552752537501L},
        Field{0.112444671031563226059L}};
      (*this)[6] = {
        Vector{0.73896247490522224783L},
        Field{0.146021341839841878937L}};
      (*this)[7] = {
        Vector{0.261037525094777752169L},
        Field{0.146021341839841878937L}};
      (*this)[8] = {
        Vector{0.582639478833193512313L},
        Field{0.163769880591948728328L}};
      (*this)[9] = {
        Vector{0.417360521166806487686L},
        Field{0.163769880591948728328L}};
      break;

    // order 18,19
    case 18 :
    case 19 :
      this->order_ = 19;
      this->resize(11);
      (*this)[0] = {
        Vector{1.0L},
        Field{0.00909090909090909090909L}};
      (*this)[1] = {
        Vector{0.0L},
        Field{0.00909090909090909090909L}};
      (*this)[2] = {
        Vector{0.967000715204029567166L},
        Field{0.0548061366334974322307L}};
      (*this)[3] = {
        Vector{0.0329992847959704328338L},
        Field{0.0548061366334974322307L}};
      (*this)[4] = {
        Vector{0.892241736831572209311L},
        Field{0.093584940890152602054L}};
      (*this)[5] = {
        Vector{0.107758263168427790688L},
        Field{0.093584940890152602054L}};
      (*this)[6] = {
        Vector{0.782617663498102503235L},
        Field{0.12402405213201415702L}};
      (*this)[7] = {
        Vector{0.217382336501897496764L},
        Field{0.12402405213201415702L}};
      (*this)[8] = {
        Vector{0.352120932206530304284L},
        Field{0.143439562389504044339L}};
      (*this)[9] = {
        Vector{0.647879067793469695715L},
        Field{0.143439562389504044339L}};
      (*this)[10] = {
        Vector{0.5L},
        Field{0.150108797727845346892L}};
      break;

    // order 20,21
    case 20 :
    case 21 :
      this->order_ = 21;
      this->resize(12);
      (*this)[0] = {
        Vector{1.0L},
        Field{0.00757575757575757575757L}};
      (*this)[1] = {
        Vector{0.0L},
        Field{0.00757575757575757575757L}};
      (*this)[2] = {
        Vector{0.972449636111441111703L},
        Field{0.0458422587065980653341L}};
      (*this)[3] = {
        Vector{0.0275503638885588882962L},
        Field{0.0458422587065980653341L}};
      (*this)[4] = {
        Vector{0.909639660822003339174L},
        Field{0.0789873527821850575823L}};
      (*this)[5] = {
        Vector{0.0903603391779966608256L},
        Field{0.0789873527821850575823L}};
      (*this)[6] = {
        Vector{0.183561923484069661168L},
        Field{0.106254208880510572679L}};
      (*this)[7] = {
        Vector{0.816438076515930338831L},
        Field{0.106254208880510572679L}};
      (*this)[8] = {
        Vector{0.300234529517325533867L},
        Field{0.125637801599600640146L}};
      (*this)[9] = {
        Vector{0.699765470482674466132L},
        Field{0.125637801599600640146L}};
      (*this)[10] = {
        Vector{0.568276466427463777432L},
        Field{0.1357026204553480885L}};
      (*this)[11] = {
        Vector{0.431723533572536222567L},
        Field{0.1357026204553480885L}};
      break;

    // order 22,23
    case 22 :
    case 23 :
      this->order_ = 23;
      this->resize(13);
      (*this)[0] = {
        Vector{0.0L},
        Field{0.00641025641025641025641L}};
      (*this)[1] = {
        Vector{1.0L},
        Field{0.00641025641025641025641L}};
      (*this)[2] = {
        Vector{0.0233450766789180440515L},
        Field{0.0389008433734094638967L}};
      (*this)[3] = {
        Vector{0.976654923321081955948L},
        Field{0.0389008433734094638967L}};
      (*this)[4] = {
        Vector{0.923173782325936158432L},
        Field{0.0674909633448041745599L}};
      (*this)[5] = {
        Vector{0.076826217674063841567L},
        Field{0.0674909633448041745599L}};
      (*this)[6] = {
        Vector{0.843094234540878713036L},
        Field{0.0918234326017750460037L}};
      (*this)[7] = {
        Vector{0.156905765459121286963L},
        Field{0.0918234326017750460037L}};
      (*this)[8] = {
        Vector{0.741454910545668100873L},
        Field{0.110383896783055043042L}};
      (*this)[9] = {
        Vector{0.258545089454331899126L},
        Field{0.110383896783055043042L}};
      (*this)[10] = {
        Vector{0.624643465053119996284L},
        Field{0.122007895153338178229L}};
      (*this)[11] = {
        Vector{0.375356534946880003715L},
        Field{0.122007895153338178229L}};
      (*this)[12] = {
        Vector{0.5L},
        Field{0.125965424666723368022L}};
      break;

    // order 24,25
    case 24 :
    case 25 :
      this->order_ = 25;
      this->resize(14);
      (*this)[0] = {
        Vector{0.0L},
        Field{0.00549450549450549450549L}};
      (*this)[1] = {
        Vector{1.0L},
        Field{0.00549450549450549450549L}};
      (*this)[2] = {
        Vector{0.979967522633630450677L},
        Field{0.033418642248840642317L}};
      (*this)[3] = {
        Vector{0.0200324773663695493224L},
        Field{0.033418642248840642317L}};
      (*this)[4] = {
        Vector{0.9339005269151736255L},
        Field{0.0582933279493558257704L}};
      (*this)[5] = {
        Vector{0.0660994730848263744998L},
        Field{0.0582933279493558257704L}};
      (*this)[6] = {
        Vector{0.135565700454336929707L},
        Field{0.0800109258814760712064L}};
      (*this)[7] = {
        Vector{0.864434299545663070292L},
        Field{0.0800109258814760712064L}};
      (*this)[8] = {
        Vector{0.775319701464323527658L},
        Field{0.0974130746867080593201L}};
      (*this)[9] = {
        Vector{0.224680298535676472341L},
        Field{0.0974130746867080593201L}};
      (*this)[10] = {
        Vector{0.328637993328643577478L},
        Field{0.109563126504885377435L}};
      (*this)[11] = {
        Vector{0.671362006671356422521L},
        Field{0.109563126504885377435L}};
      (*this)[12] = {
        Vector{0.558165934441851933829L},
        Field{0.115806397234228529444L}};
      (*this)[13] = {
        Vector{0.44183406555814806617L},
        Field{0.115806397234228529444L}};
      break;

    // order 26,27
    case 26 :
    case 27 :
      this->order_ = 27;
      this->resize(15);
      (*this)[0] = {
        Vector{0.0L},
        Field{0.00476190476190476190476L}};
      (*this)[1] = {
        Vector{1.0L},
        Field{0.00476190476190476190476L}};
      (*this)[2] = {
        Vector{0.982622963251919286397L},
        Field{0.0290149465143006245484L}};
      (*this)[3] = {
        Vector{0.017377036748080713602L},
        Field{0.0290149465143006245484L}};
      (*this)[4] = {
        Vector{0.0574589778885118505872L},
        Field{0.0508300351628590338018L}};
      (*this)[5] = {
        Vector{0.942541022111488149412L},
        Field{0.0508300351628590338018L}};
      (*this)[6] = {
        Vector{0.118240155024092399647L},
        Field{0.0702558499012140547302L}};
      (*this)[7] = {
        Vector{0.881759844975907600352L},
        Field{0.0702558499012140547302L}};
      (*this)[8] = {
        Vector{0.803126602734922855561L},
        Field{0.086394823626800474526L}};
      (*this)[9] = {
        Vector{0.196873397265077144438L},
        Field{0.086394823626800474526L}};
      (*this)[10] = {
        Vector{0.71031902735683624046L},
        Field{0.0984936179823066780462L}};
      (*this)[11] = {
        Vector{0.289680972643163759539L},
        Field{0.0984936179823066780462L}};
      (*this)[12] = {
        Vector{0.392323022318102880887L},
        Field{0.105986792963410460063L}};
      (*this)[13] = {
        Vector{0.607676977681897119112L},
        Field{0.105986792963410460063L}};
      (*this)[14] = {
        Vector{0.5L},
        Field{0.108524058174407824757L}};
      break;

    // order 28,29
    case 28 :
    case 29 :
      this->order_ = 29;
      this->resize(16);
      (*this)[0] = {
        Vector{1.0L},
        Field{0.00416666666666666666666L}};
      (*this)[1] = {
        Vector{0.0L},
        Field{0.00416666666666666666666L}};
      (*this)[2] = {
        Vector{0.984784023135108966476L},
        Field{0.0254251805029599527016L}};
      (*this)[3] = {
        Vector{0.0152159768648910335238L},
        Field{0.0254251805029599527016L}};
      (*this)[4] = {
        Vector{0.0503997334532639535026L},
        Field{0.0446968486629654004955L}};
      (*this)[5] = {
        Vector{0.949600266546736046497L},
        Field{0.0446968486629654004955L}};
      (*this)[6] = {
        Vector{0.896004145930907531965L},
        Field{0.0621276910662570491747L}};
      (*this)[7] = {
        Vector{0.103995854069092468034L},
        Field{0.0621276910662570491747L}};
      (*this)[8] = {
        Vector{0.173805648558753455266L},
        Field{0.0770134904035821404078L}};
      (*this)[9] = {
        Vector{0.826194351441246544733L},
        Field{0.0770134904035821404078L}};
      (*this)[10] = {
        Vector{0.74302971094356880589L},
        Field{0.0887459566958520626505L}};
      (*this)[11] = {
        Vector{0.256970289056431194109L},
        Field{0.0887459566958520626505L}};
      (*this)[12] = {
        Vector{0.649915234450381604049L},
        Field{0.0968450119126017921584L}};
      (*this)[13] = {
        Vector{0.35008476554961839595L},
        Field{0.0968450119126017921584L}};
      (*this)[14] = {
        Vector{0.449336863239025276078L},
        Field{0.100979154089114935744L}};
      (*this)[15] = {
        Vector{0.550663136760974723921L},
        Field{0.100979154089114935744L}};
      break;

    // order 30,31
    case 30 :
    case 31 :
      this->order_ = 31;
      this->resize(17);
      (*this)[0] = {
        Vector{0.0L},
        Field{0.00367647058823529411764L}};
      (*this)[1] = {
        Vector{1.0L},
        Field{0.00367647058823529411764L}};
      (*this)[2] = {
        Vector{0.986566088315709157078L},
        Field{0.0224609702716271048237L}};
      (*this)[3] = {
        Vector{0.0134339116842908429215L},
        Field{0.0224609702716271048237L}};
      (*this)[4] = {
        Vector{0.955439997957786797811L},
        Field{0.0395991352518435595951L}};
      (*this)[5] = {
        Vector{0.044560002042213202188L},
        Field{0.0395991352518435595951L}};
      (*this)[6] = {
        Vector{0.907848125610885153553L},
        Field{0.0552964545035140806878L}};
      (*this)[7] = {
        Vector{0.0921518743891148464466L},
        Field{0.0552964545035140806878L}};
      (*this)[8] = {
        Vector{0.154485509686157647302L},
        Field{0.0689938731009632795281L}};
      (*this)[9] = {
        Vector{0.845514490313842352697L},
        Field{0.0689938731009632795281L}};
      (*this)[10] = {
        Vector{0.770692699665050769561L},
        Field{0.0801973309988107697581L}};
      (*this)[11] = {
        Vector{0.229307300334949230438L},
        Field{0.0801973309988107697581L}};
      (*this)[12] = {
        Vector{0.686087216782738520953L},
        Field{0.0885021267578289352184L}};
      (*this)[13] = {
        Vector{0.313912783217261479046L},
        Field{0.0885021267578289352184L}};
      (*this)[14] = {
        Vector{0.405244013240841305847L},
        Field{0.093608169838809617946L}};
      (*this)[15] = {
        Vector{0.594755986759158694152L},
        Field{0.093608169838809617946L}};
      (*this)[16] = {
        Vector{0.5L},
        Field{0.0953309373767347166497L}};
      break;

    default :
      DUNE_THROW(QuadratureOrderOutOfRange, "Quadrature rule " << p << " not supported!");
    }
  }


} // namespace Dune

#endif // DUNE_GEOMETRY_QUADRATURE_GaussLobatto_HH
