// -*- tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 2 -*-
// vi: set et ts=4 sw=2 sts=2:
//
// WARNING
// This file is automatically generated by gaussradau.mac! Don't edit by hand!
#ifndef DUNE_GEOMETRY_QUADRATURE_GaussRadauRight_HH
#define DUNE_GEOMETRY_QUADRATURE_GaussRadauRight_HH

#ifndef DUNE_INCLUDING_IMPLEMENTATION
#error This is a private header that should not be included directly.
#error Use #include <dune/geometry/quadraturerules.hh> instead.
#endif

namespace Dune {

  /************************************************
   * Quadraturerule for 1d line
   *************************************************/

  template<typename ct>
  class GaussRadauRightQuadratureRule : public QuadratureRule<ct,1>
  {
  public:
    /** brief The highest quadrature order available */
    enum { highest_order = 30 };

    using Field = typename QuadraturePoint<ct,1>::Field;
    using Vector = typename QuadraturePoint<ct,1>::Vector;

  private:
    friend class QuadratureRuleFactory<ct,1>;
    GaussRadauRightQuadratureRule (int p);
  };

  template<typename ct>
  GaussRadauRightQuadratureRule<ct>::GaussRadauRightQuadratureRule (int p)
    : QuadratureRule<ct,1>(GeometryTypes::line)
  {
    switch (p)
    {
    case 0 :
      this->order_ = 0;
      this->resize(1);
      (*this)[0] = {
        Vector{1.0L},
        Field{1.0L}};
      break;

    // order 1,2
    case 1 :
    case 2 :
      this->order_ = 2;
      this->resize(2);
      (*this)[0] = {
        Vector{1.0L},
        Field{0.25L}};
      (*this)[1] = {
        Vector{0.333333333333333333333L},
        Field{0.75L}};
      break;

    // order 3,4
    case 3 :
    case 4 :
      this->order_ = 4;
      this->resize(3);
      (*this)[0] = {
        Vector{1.0L},
        Field{0.111111111111111111111L}};
      (*this)[1] = {
        Vector{0.15505102572168219018L},
        Field{0.37640306270046727505L}};
      (*this)[2] = {
        Vector{0.644948974278317809819L},
        Field{0.512485826188421613838L}};
      break;

    // order 5,6
    case 5 :
    case 6 :
      this->order_ = 6;
      this->resize(4);
      (*this)[0] = {
        Vector{1.0L},
        Field{0.0625L}};
      (*this)[1] = {
        Vector{0.0885879595127039473955L},
        Field{0.220462211176768375275L}};
      (*this)[2] = {
        Vector{0.787659461760847056025L},
        Field{0.328844319980059743944L}};
      (*this)[3] = {
        Vector{0.409466864440734710864L},
        Field{0.38819346884317188078L}};
      break;

    // order 7,8
    case 7 :
    case 8 :
      this->order_ = 8;
      this->resize(5);
      (*this)[0] = {
        Vector{1.0L},
        Field{0.0399999999999999999999L}};
      (*this)[1] = {
        Vector{0.0571041961145176821931L},
        Field{0.143713560791225941323L}};
      (*this)[2] = {
        Vector{0.860240135656219447847L},
        Field{0.223103901083570744402L}};
      (*this)[3] = {
        Vector{0.27684301363812382768L},
        Field{0.281356015149462060192L}};
      (*this)[4] = {
        Vector{0.583590432368916820056L},
        Field{0.311826522975741254081L}};
      break;

    // order 9,10
    case 9 :
    case 10 :
      this->order_ = 10;
      this->resize(6);
      (*this)[0] = {
        Vector{0.999999999999999999999L},
        Field{0.0277777777777777777777L}};
      (*this)[1] = {
        Vector{0.0398098570514687423408L},
        Field{0.100794192626740420104L}};
      (*this)[2] = {
        Vector{0.901464914201173573876L},
        Field{0.159820376610255483272L}};
      (*this)[3] = {
        Vector{0.198013417873608172535L},
        Field{0.208450667155953869479L}};
      (*this)[4] = {
        Vector{0.695464273353636094514L},
        Field{0.242693594234484958079L}};
      (*this)[5] = {
        Vector{0.437974810247386144005L},
        Field{0.260463391594787491285L}};
      break;

    // order 11,12
    case 11 :
    case 12 :
      this->order_ = 12;
      this->resize(7);
      (*this)[0] = {
        Vector{1.0L},
        Field{0.0204081632653061224489L}};
      (*this)[1] = {
        Vector{0.029316427159784891972L},
        Field{0.0744942355560103179332L}};
      (*this)[2] = {
        Vector{0.926945671319741114851L},
        Field{0.119613744612656202893L}};
      (*this)[3] = {
        Vector{0.148078599668484291849L},
        Field{0.159102115733650740872L}};
      (*this)[4] = {
        Vector{0.769233862030054500916L},
        Field{0.190474936822115576902L}};
      (*this)[5] = {
        Vector{0.336984690281154299097L},
        Field{0.212351889502977804199L}};
      (*this)[6] = {
        Vector{0.558671518771550132081L},
        Field{0.223554914507283234749L}};
      break;

    // order 13,14
    case 13 :
    case 14 :
      this->order_ = 14;
      this->resize(8);
      (*this)[0] = {
        Vector{1.0L},
        Field{0.015625L}};
      (*this)[1] = {
        Vector{0.0224793864387124981088L},
        Field{0.0572544073721285996711L}};
      (*this)[2] = {
        Vector{0.943737439463077853534L},
        Field{0.0926790774014896392703L}};
      (*this)[3] = {
        Vector{0.114679053160904231909L},
        Field{0.124823950664932481628L}};
      (*this)[4] = {
        Vector{0.819759308263107635012L},
        Field{0.152065310323392564487L}};
      (*this)[5] = {
        Vector{0.265789822784589468476L},
        Field{0.173507397817250640114L}};
      (*this)[6] = {
        Vector{0.647375282886830362626L},
        Field{0.188258772694559278286L}};
      (*this)[7] = {
        Vector{0.452846373669444616998L},
        Field{0.195786083726246796541L}};
      break;

    // order 15,16
    case 15 :
    case 16 :
      this->order_ = 16;
      this->resize(9);
      (*this)[0] = {
        Vector{1.0L},
        Field{0.0123456790123456790123L}};
      (*this)[1] = {
        Vector{0.0177799151473634518132L},
        Field{0.0453572524616414585064L}};
      (*this)[2] = {
        Vector{0.955366044710030149266L},
        Field{0.0738270095231576929097L}};
      (*this)[3] = {
        Vector{0.0913236078997939560037L},
        Field{0.10027664901227597871L}};
      (*this)[4] = {
        Vector{0.855633742957854428514L},
        Field{0.12359468910229652618L}};
      (*this)[5] = {
        Vector{0.214308479395630758357L},
        Field{0.143193348178615585573L}};
      (*this)[6] = {
        Vector{0.713175242855569481051L},
        Field{0.158421887835218989169L}};
      (*this)[7] = {
        Vector{0.37193216458327230243L},
        Field{0.168846983487964792901L}};
      (*this)[8] = {
        Vector{0.545186684803426649032L},
        Field{0.174136501386483297035L}};
      break;

    // order 17,18
    case 17 :
    case 18 :
      this->order_ = 18;
      this->resize(10);
      (*this)[0] = {
        Vector{1.0L},
        Field{0.01L}};
      (*this)[1] = {
        Vector{0.0144124096488765486328L},
        Field{0.0368085027433792494655L}};
      (*this)[2] = {
        Vector{0.963742187116790539058L},
        Field{0.0601483352787408157586L}};
      (*this)[3] = {
        Vector{0.0743873897091960446359L},
        Field{0.0821880063684607378508L}};
      (*this)[4] = {
        Vector{0.881921021210001299807L},
        Field{0.102135065939500337777L}};
      (*this)[5] = {
        Vector{0.176116656162995281863L},
        Field{0.119596715857189856688L}};
      (*this)[6] = {
        Vector{0.762823015185039614682L},
        Field{0.134097418920589348029L}};
      (*this)[7] = {
        Vector{0.309667579927637817059L},
        Field{0.145305082416459155573L}};
      (*this)[8] = {
        Vector{0.618117234695294024639L},
        Field{0.152929643862211310508L}};
      (*this)[9] = {
        Vector{0.461970401081010934883L},
        Field{0.156791228613469188347L}};
      break;

    // order 19,20
    case 19 :
    case 20 :
      this->order_ = 20;
      this->resize(11);
      (*this)[0] = {
        Vector{0.999999999999999999999L},
        Field{0.0082644628099173553719L}};
      (*this)[1] = {
        Vector{0.0119176134324155969097L},
        Field{0.0304625489060655673536L}};
      (*this)[2] = {
        Vector{0.969970967838513502956L},
        Field{0.0499230409539840319478L}};
      (*this)[3] = {
        Vector{0.0617320718771481255226L},
        Field{0.068516841066601128155L}};
      (*this)[4] = {
        Vector{0.901710987790146770348L},
        Field{0.0856588096033299182433L}};
      (*this)[5] = {
        Vector{0.147111449643070240427L},
        Field{0.101081554270012209174L}};
      (*this)[6] = {
        Vector{0.800978921036898845137L},
        Field{0.1144330619244883122L}};
      (*this)[7] = {
        Vector{0.261159676008456240266L},
        Field{0.125462688848564197324L}};
      (*this)[8] = {
        Vector{0.675944461676665107357L},
        Field{0.133933543094842088903L}};
      (*this)[9] = {
        Vector{0.394639846885786842961L},
        Field{0.139680666551691522594L}};
      (*this)[10] = {
        Vector{0.536738765715660632873L},
        Field{0.14258278197050366873L}};
      break;

    // order 21,22
    case 21 :
    case 22 :
      this->order_ = 22;
      this->resize(12);
      (*this)[0] = {
        Vector{0.999999999999999999999L},
        Field{0.00694444444444444444444L}};
      (*this)[1] = {
        Vector{0.010018280461680405843L},
        Field{0.025624049603634648734L}};
      (*this)[2] = {
        Vector{0.974726379602479650246L},
        Field{0.0420860674693404881207L}};
      (*this)[3] = {
        Vector{0.0520354511271805525835L},
        Field{0.0579537401458691963751L}};
      (*this)[4] = {
        Vector{0.916958386552594853293L},
        Field{0.0727818344269975642612L}};
      (*this)[5] = {
        Vector{0.124619225144443073735L},
        Field{0.086385319656654282153L}};
      (*this)[6] = {
        Vector{0.83082489962281857403L},
        Field{0.098499267413044817328L}};
      (*this)[7] = {
        Vector{0.222840607043837855507L},
        Field{0.108934439513096219424L}};
      (*this)[8] = {
        Vector{0.722203284890967925563L},
        Field{0.117501557572492919674L}};
      (*this)[9] = {
        Vector{0.340008157914665188233L},
        Field{0.124060780402004979701L}};
      (*this)[10] = {
        Vector{0.598497279767139183227L},
        Field{0.128495669076353888063L}};
      (*this)[11] = {
        Vector{0.468137613089584042083L},
        Field{0.130732830276066551719L}};
      break;

    // order 23,24
    case 23 :
    case 24 :
      this->order_ = 24;
      this->resize(13);
      (*this)[0] = {
        Vector{0.999999999999999999999L},
        Field{0.00591715976331360946745L}};
      (*this)[1] = {
        Vector{0.00853905498842741936866L},
        Field{0.0218514516339510374144L}};
      (*this)[2] = {
        Vector{0.978437936834149639091L},
        Field{0.0359512081462477644698L}};
      (*this)[3] = {
        Vector{0.0444464631554077230254L},
        Field{0.0496339034409235429923L}};
      (*this)[4] = {
        Vector{0.928942101264411017848L},
        Field{0.0625519171655761790668L}};
      (*this)[5] = {
        Vector{0.106854490883476657634L},
        Field{0.0745754750450001025757L}};
      (*this)[6] = {
        Vector{0.85455254376493588079L},
        Field{0.0855017302353083212318L}};
      (*this)[7] = {
        Vector{0.192151054529854040991L},
        Field{0.0951868577798158661273L}};
      (*this)[8] = {
        Vector{0.759598889525227053742L},
        Field{0.103480305727938537315L}};
      (*this)[9] = {
        Vector{0.295380884262580221622L},
        Field{0.110267114644225732345L}};
      (*this)[10] = {
        Vector{0.649600650277254992766L},
        Field{0.115444431443497717006L}};
      (*this)[11] = {
        Vector{0.410545081201457682489L},
        Field{0.118939273830356015671L}};
      (*this)[12] = {
        Vector{0.530950849312817670628L},
        Field{0.120699171143845574315L}};
      break;

    // order 25,26
    case 25 :
    case 26 :
      this->order_ = 26;
      this->resize(14);
      (*this)[0] = {
        Vector{0.999999999999999999999L},
        Field{0.00510204081632653061224L}};
      (*this)[1] = {
        Vector{0.00736465102608932165069L},
        Field{0.0188535816349484571387L}};
      (*this)[2] = {
        Vector{0.98138963498901214856L},
        Field{0.031061008453885730083L}};
      (*this)[3] = {
        Vector{0.0383981387396783503768L},
        Field{0.0429702677214902015446L}};
      (*this)[4] = {
        Vector{0.938524459100731012397L},
        Field{0.0543038613721814134133L}};
      (*this)[5] = {
        Vector{0.0925952246990026352828L},
        Field{0.0649698343686711739037L}};
      (*this)[6] = {
        Vector{0.873694821306689419367L},
        Field{0.0748102696765606779752L}};
      (*this)[7] = {
        Vector{0.167251011391557731495L},
        Field{0.083714863945543139495L}};
      (*this)[8] = {
        Vector{0.790157028273437485552L},
        Field{0.0915635010628648270619L}};
      (*this)[9] = {
        Vector{0.258623540705762516589L},
        Field{0.0982627592264912151623L}};
      (*this)[10] = {
        Vector{0.692101001719601656897L},
        Field{0.103724881667587836334L}};
      (*this)[11] = {
        Vector{0.362131397282238800408L},
        Field{0.10788355030230942569L}};
      (*this)[12] = {
        Vector{0.584443964021340455504L},
        Field{0.110684905749785474465L}};
      (*this)[13] = {
        Vector{0.472584386004117725175L},
        Field{0.112094674001353897119L}};
      break;

    // order 27,28
    case 27 :
    case 28 :
      this->order_ = 28;
      this->resize(15);
      (*this)[0] = {
        Vector{0.999999999999999999999L},
        Field{0.00444444444444444444444L}};
      (*this)[1] = {
        Vector{0.00641676079281845681082L},
        Field{0.0164321957922967661265L}};
      (*this)[2] = {
        Vector{0.983775234098600238281L},
        Field{0.0271013900243222471691L}};
      (*this)[3] = {
        Vector{0.0335014045320131400359L},
        Field{0.0375541963802532198664L}};
      (*this)[4] = {
        Vector{0.946302700060275383533L},
        Field{0.0475647997302404496019L}};
      (*this)[5] = {
        Vector{0.0809854996819551843924L},
        Field{0.0570676017448763765065L}};
      (*this)[6] = {
        Vector{0.88934280881951553969L},
        Field{0.0659377312524758160931L}};
      (*this)[7] = {
        Vector{0.146804867681213729923L},
        Field{0.0740897635017336269623L}};
      (*this)[8] = {
        Vector{0.815389739443474641973L},
        Field{0.0814272386519163147243L}};
      (*this)[9] = {
        Vector{0.228084270649257991534L},
        Field{0.0878744363212238428351L}};
      (*this)[10] = {
        Vector{0.727676452889264685436L},
        Field{0.0933575729197254540418L}};
      (*this)[11] = {
        Vector{0.321271743988936174402L},
        Field{0.0978187515225580582367L}};
      (*this)[12] = {
        Vector{0.630036688370403957884L},
        Field{0.101207593515309214936L}};
      (*this)[13] = {
        Vector{0.42229465730757025784L},
        Field{0.103487980124776877739L}};
      (*this)[14] = {
        Vector{0.526737861339873032053L},
        Field{0.104634304073847290715L}};
      break;

    // order 29,30
    case 29 :
    case 30 :
      this->order_ = 30;
      this->resize(16);
      (*this)[0] = {
        Vector{1.0L},
        Field{0.00390624999999999999999L}};
      (*this)[1] = {
        Vector{0.0056406889725117097575L},
        Field{0.0144485695084071642457L}};
      (*this)[2] = {
        Vector{0.985730545263174225265L},
        Field{0.0238511134738428602325L}};
      (*this)[3] = {
        Vector{0.0294822986479424866316L},
        Field{0.0330947543050682173723L}};
      (*this)[4] = {
        Vector{0.952700409905833314338L},
        Field{0.0419926407224825890035L}};
      (*this)[5] = {
        Vector{0.0714129531151588400547L},
        Field{0.0504978398108919543621L}};
      (*this)[6] = {
        Vector{0.902286700679378026631L},
        Field{0.0585101765519300285152L}};
      (*this)[7] = {
        Vector{0.129831025553591055971L},
        Field{0.0659628499665340667224L}};
      (*this)[8] = {
        Vector{0.836430960605610123975L},
        Field{0.0727777726101011214353L}};
      (*this)[9] = {
        Vector{0.202492755050104047568L},
        Field{0.0788934609021010101425L}};
      (*this)[10] = {
        Vector{0.757664739031342711997L},
        Field{0.0842481989249612450181L}};
      (*this)[11] = {
        Vector{0.286606086257527059984L},
        Field{0.0887923963763697559481L}};
      (*this)[12] = {
        Vector{0.669015195029959876538L},
        Field{0.0924808907443326797832L}};
      (*this)[13] = {
        Vector{0.378938688646978038106L},
        Field{0.0952791471276775444131L}};
      (*this)[14] = {
        Vector{0.573889160906685880671L},
        Field{0.0971595448557839216716L}};
      (*this)[15] = {
        Vector{0.475942308463234860572L},
        Field{0.0981043941195158411335L}};
      break;

    default :
      DUNE_THROW(QuadratureOrderOutOfRange, "Quadrature rule " << p << " not supported!");
    }
  }


} // namespace Dune

#endif // DUNE_GEOMETRY_QUADRATURE_GaussRadauRight_HH
